<a href="https://colab.research.google.com/github/ananyaslnkh/data-engineering/blob/main/De_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
from google.colab import files
uploaded = files.upload()

Saving world_population_by_country_2023_modified.csv to world_population_by_country_2023_modified (1).csv

In [ ]:
df = pd.read_csv('world_population_by_country_2023_modified.csv')

In [ ]:
print(df)

             country  population  yearly_change  net_change  density  \
0        Afghanistan    42239854           2.70     1111083       65
1            Albania     2832439          -0.35       -9882      103
2            Algeria    45606480           1.57      703255       19
3     American Samoa       43914          -0.81        -359      220
4            Andorra       80088           0.33         264      170
..               ...         ...            ...         ...      ...
229  Wallis & Futuna       11502          -0.60         -70       82
230   Western Sahara      587259           1.96       11273        2
231            Yemen    34449825           2.24      753211       65
232           Zambia    20569737           2.76      552062       28
233         Zimbabwe    16665409           2.11      344872       43

     land_area  net_migrants  fertility_rate  median_age  population_urban  \
0       652860        -65846             4.4        17.0              26.0
1        27400         -8000             1.4        38.0              67.0
2      2381740         -9999             2.8        28.0              75.0
3          200          -790             2.2        29.0               NaN
4          470           200             1.1        43.0              85.0
..         ...           ...             ...         ...               ...
229        140          -119             1.9        37.0               0.0
230     266000          5600             2.2        32.0              95.0
231     527970        -29914             3.6        19.0              37.0
232     743390         -5000             4.2        17.0              46.0
233     386850         -9999             3.4        18.0              37.0

     world_share
0           0.53
1           0.04
2           0.57
3           0.00
4           0.00
..           ...
229         0.00
230         0.01
231         0.43
232         0.26
233         0.21

[234 rows x 11 columns]

In [ ]:
print(df.isnull().sum())

country              1
population           1
yearly_change        1
net_change           1
density              3
land_area            1
net_migrants         2
fertility_rate       2
median_age           3
population_urban    19
world_share          1
dtype: int64

In [ ]:
drop_all = df.dropna()
print(drop_all.head(15))

                country   population  yearly_change  net_change  density  \
0           Afghanistan   42239854.0           2.70   1111083.0     65.0
1               Albania    2832439.0          -0.35     -9882.0    103.0
2               Algeria   45606480.0           1.57    703255.0     19.0
4               Andorra      80088.0           0.33       264.0    170.0
5                Angola   36684202.0           3.08   1095215.0     29.0
7   Antigua and Barbuda      94298.0           0.57       535.0    214.0
8             Argentina   45773884.0           0.58    263566.0     17.0
10                Aruba     106277.0          -0.16      -168.0    590.0
12              Austria    8958960.0           0.22     19343.0    109.0
13           Azerbaijan   10412651.0           0.53     54577.0    126.0
14              Bahamas     412623.0           0.64      2639.0     41.0
16           Bangladesh  172954319.0           1.03   1767947.0   1329.0
17             Barbados     281995.0           0.13       360.0    656.0
18              Belarus    9498238.0          -0.39    -36716.0     47.0
19              Belgium   11686140.0           0.26     30210.0    386.0

    land_area  net_migrants  fertility_rate  median_age  population_urban  \
0    652860.0      -65846.0             4.4        17.0              26.0
1     27400.0       -8000.0             1.4        38.0              67.0
2   2381740.0       -9999.0             2.8        28.0              75.0
4       470.0         200.0             1.1        43.0              85.0
5   1246700.0       -1000.0             5.1        16.0              68.0
7       440.0           0.0             1.6        36.0              28.0
8   2736690.0        3718.0             1.9        32.0              94.0
10      180.0         157.0             1.2        42.0              45.0
12    82409.0       19999.0             1.5        43.0              59.0
13    82658.0           0.0             1.7        32.0              57.0
14    10010.0        1000.0             1.4        33.0              85.0
16   130170.0     -309977.0             1.9        27.0              41.0
17      430.0         -80.0             1.6        40.0              32.0
18   202910.0       -4282.0             1.5        41.0              80.0
19    30280.0       23999.0             1.6        41.0              99.0

    world_share
0          0.53
1          0.04
2          0.57
4          0.00
5          0.46
7          0.00
8          0.57
10         0.00
12         0.11
13         0.13
14         0.01
16         2.15
17         0.00
18         0.12
19         0.15

In [ ]:
drop_row = df.dropna(how='all')
print(drop_row.head(15))

                country  population  yearly_change  net_change  density  \
0           Afghanistan  42239854.0           2.70   1111083.0     65.0
1               Albania   2832439.0          -0.35     -9882.0    103.0
2               Algeria  45606480.0           1.57    703255.0     19.0
3        American Samoa     43914.0          -0.81      -359.0    220.0
4               Andorra     80088.0           0.33       264.0    170.0
5                Angola  36684202.0           3.08   1095215.0     29.0
6              Anguilla     15899.0           0.26        42.0      NaN
7   Antigua and Barbuda     94298.0           0.57       535.0    214.0
8             Argentina  45773884.0           0.58    263566.0     17.0
10                Aruba    106277.0          -0.16      -168.0    590.0
11            Australia  26439111.0           1.00    261698.0      NaN
12              Austria   8958960.0           0.22     19343.0    109.0
13           Azerbaijan  10412651.0           0.53     54577.0    126.0
14              Bahamas    412623.0           0.64      2639.0     41.0
15              Bahrain   1485509.0           0.90     13276.0   1955.0

    land_area  net_migrants  fertility_rate  median_age  population_urban  \
0    652860.0      -65846.0             4.4        17.0              26.0
1     27400.0       -8000.0             1.4        38.0              67.0
2   2381740.0       -9999.0             2.8        28.0              75.0
3       200.0        -790.0             2.2        29.0               NaN
4       470.0         200.0             1.1        43.0              85.0
5   1246700.0       -1000.0             5.1        16.0              68.0
6        90.0           NaN             1.3         NaN              98.0
7       440.0           0.0             1.6        36.0              28.0
8   2736690.0        3718.0             1.9        32.0              94.0
10      180.0         157.0             1.2        42.0              45.0
11  7682300.0      139991.0             1.6        38.0              86.0
12    82409.0       19999.0             1.5        43.0              59.0
13    82658.0           0.0             1.7        32.0              57.0
14    10010.0        1000.0             1.4        33.0              85.0
15      760.0           0.0             1.8        34.0               NaN

    world_share
0          0.53
1          0.04
2          0.57
3          0.00
4          0.00
5          0.46
6          0.00
7          0.00
8          0.57
10         0.00
11         0.33
12         0.11
13         0.13
14         0.01
15         0.02

In [ ]:
drop_more_than_2 = df.dropna(thresh=df.shape[1] - 2)
print(drop_more_than_2.head(10))

                country  population  yearly_change  net_change  density  \
0           Afghanistan  42239854.0           2.70   1111083.0     65.0
1               Albania   2832439.0          -0.35     -9882.0    103.0
2               Algeria  45606480.0           1.57    703255.0     19.0
3        American Samoa     43914.0          -0.81      -359.0    220.0
4               Andorra     80088.0           0.33       264.0    170.0
5                Angola  36684202.0           3.08   1095215.0     29.0
7   Antigua and Barbuda     94298.0           0.57       535.0    214.0
8             Argentina  45773884.0           0.58    263566.0     17.0
10                Aruba    106277.0          -0.16      -168.0    590.0
11            Australia  26439111.0           1.00    261698.0      NaN

    land_area  net_migrants  fertility_rate  median_age  population_urban  \
0    652860.0      -65846.0             4.4        17.0              26.0
1     27400.0       -8000.0             1.4        38.0              67.0
2   2381740.0       -9999.0             2.8        28.0              75.0
3       200.0        -790.0             2.2        29.0               NaN
4       470.0         200.0             1.1        43.0              85.0
5   1246700.0       -1000.0             5.1        16.0              68.0
7       440.0           0.0             1.6        36.0              28.0
8   2736690.0        3718.0             1.9        32.0              94.0
10      180.0         157.0             1.2        42.0              45.0
11  7682300.0      139991.0             1.6        38.0              86.0

    world_share
0          0.53
1          0.04
2          0.57
3          0.00
4          0.00
5          0.46
7          0.00
8          0.57
10         0.00
11         0.33

In [ ]:
drop_specific = df.dropna(subset=['net_migrants'])
print(drop_specific.head(15))

                country   population  yearly_change  net_change  density  \
0           Afghanistan   42239854.0           2.70   1111083.0     65.0
1               Albania    2832439.0          -0.35     -9882.0    103.0
2               Algeria   45606480.0           1.57    703255.0     19.0
3        American Samoa      43914.0          -0.81      -359.0    220.0
4               Andorra      80088.0           0.33       264.0    170.0
5                Angola   36684202.0           3.08   1095215.0     29.0
7   Antigua and Barbuda      94298.0           0.57       535.0    214.0
8             Argentina   45773884.0           0.58    263566.0     17.0
10                Aruba     106277.0          -0.16      -168.0    590.0
11            Australia   26439111.0           1.00    261698.0      NaN
12              Austria    8958960.0           0.22     19343.0    109.0
13           Azerbaijan   10412651.0           0.53     54577.0    126.0
14              Bahamas     412623.0           0.64      2639.0     41.0
15              Bahrain    1485509.0           0.90     13276.0   1955.0
16           Bangladesh  172954319.0           1.03   1767947.0   1329.0

    land_area  net_migrants  fertility_rate  median_age  population_urban  \
0    652860.0      -65846.0             4.4        17.0              26.0
1     27400.0       -8000.0             1.4        38.0              67.0
2   2381740.0       -9999.0             2.8        28.0              75.0
3       200.0        -790.0             2.2        29.0               NaN
4       470.0         200.0             1.1        43.0              85.0
5   1246700.0       -1000.0             5.1        16.0              68.0
7       440.0           0.0             1.6        36.0              28.0
8   2736690.0        3718.0             1.9        32.0              94.0
10      180.0         157.0             1.2        42.0              45.0
11  7682300.0      139991.0             1.6        38.0              86.0
12    82409.0       19999.0             1.5        43.0              59.0
13    82658.0           0.0             1.7        32.0              57.0
14    10010.0        1000.0             1.4        33.0              85.0
15      760.0           0.0             1.8        34.0               NaN
16   130170.0     -309977.0             1.9        27.0              41.0

    world_share
0          0.53
1          0.04
2          0.57
3          0.00
4          0.00
5          0.46
7          0.00
8          0.57
10         0.00
11         0.33
12         0.11
13         0.13
14         0.01
15         0.02
16         2.15

In [ ]:
df.fillna(0)

,country,population,yearly_change,net_change,density,land_area,net_migrants,fertility_rate,median_age,population_urban,world_share
0,Afghanistan,42239854.0,2.70,1111083.0,65.0,652860.0,-65846.0,4.4,17.0,26.0,0.53
1,Albania,2832439.0,-0.35,-9882.0,103.0,27400.0,-8000.0,1.4,38.0,67.0,0.04
2,Algeria,45606480.0,1.57,703255.0,19.0,2381740.0,-9999.0,2.8,28.0,75.0,0.57
3,American Samoa,43914.0,-0.81,-359.0,220.0,200.0,-790.0,2.2,29.0,0.0,0.00
4,Andorra,80088.0,0.33,264.0,170.0,470.0,200.0,1.1,43.0,85.0,0.00
...,...,...,...,...,...,...,...,...,...,...,...
229,Wallis & Futuna,11502.0,-0.60,-70.0,82.0,140.0,-119.0,1.9,37.0,0.0,0.00
230,Western Sahara,587259.0,1.96,11273.0,2.0,266000.0,5600.0,2.2,32.0,95.0,0.01
231,Yemen,34449825.0,2.24,753211.0,65.0,527970.0,-29914.0,3.6,19.0,37.0,0.43
232,Zambia,20569737.0,2.76,552062.0,28.0,743390.0,-5000.0,4.2,17.0,46.0,0.26
233,Zimbabwe,16665409.0,2.11,344872.0,43.0,386850.0,-9999.0,3.4,18.0,37.0,0.21

In [ ]:
mean = df['population_urban'].mean()
print(mean)
df['population_urban'].fillna(mean, inplace=True)
print(df)

59.51627906976744
             country  population  yearly_change  net_change  density  \
0        Afghanistan  42239854.0           2.70   1111083.0     65.0
1            Albania   2832439.0          -0.35     -9882.0    103.0
2            Algeria  45606480.0           1.57    703255.0     19.0
3     American Samoa     43914.0          -0.81      -359.0    220.0
4            Andorra     80088.0           0.33       264.0    170.0
..               ...         ...            ...         ...      ...
229  Wallis & Futuna     11502.0          -0.60       -70.0     82.0
230   Western Sahara    587259.0           1.96     11273.0      2.0
231            Yemen  34449825.0           2.24    753211.0     65.0
232           Zambia  20569737.0           2.76    552062.0     28.0
233         Zimbabwe  16665409.0           2.11    344872.0     43.0

     land_area  net_migrants  fertility_rate  median_age  population_urban  \
0     652860.0      -65846.0             4.4        17.0         26.000000
1      27400.0       -8000.0             1.4        38.0         67.000000
2    2381740.0       -9999.0             2.8        28.0         75.000000
3        200.0        -790.0             2.2        29.0         59.516279
4        470.0         200.0             1.1        43.0         85.000000
..         ...           ...             ...         ...               ...
229      140.0        -119.0             1.9        37.0          0.000000
230   266000.0        5600.0             2.2        32.0         95.000000
231   527970.0      -29914.0             3.6        19.0         37.000000
232   743390.0       -5000.0             4.2        17.0         46.000000
233   386850.0       -9999.0             3.4        18.0         37.000000

     world_share
0           0.53
1           0.04
2           0.57
3           0.00
4           0.00
..           ...
229         0.00
230         0.01
231         0.43
232         0.26
233         0.21

[234 rows x 11 columns]

In [ ]:
median = df['median_age'].median()
print(median)
df['median_age'].fillna(median, inplace=True)
print(df)

32.0
             country  population  yearly_change  net_change  density  \
0        Afghanistan  42239854.0           2.70   1111083.0     65.0
1            Albania   2832439.0          -0.35     -9882.0    103.0
2            Algeria  45606480.0           1.57    703255.0     19.0
3     American Samoa     43914.0          -0.81      -359.0    220.0
4            Andorra     80088.0           0.33       264.0    170.0
..               ...         ...            ...         ...      ...
229  Wallis & Futuna     11502.0          -0.60       -70.0     82.0
230   Western Sahara    587259.0           1.96     11273.0      2.0
231            Yemen  34449825.0           2.24    753211.0     65.0
232           Zambia  20569737.0           2.76    552062.0     28.0
233         Zimbabwe  16665409.0           2.11    344872.0     43.0

     land_area  net_migrants  fertility_rate  median_age  population_urban  \
0     652860.0      -65846.0             4.4        17.0         26.000000
1      27400.0       -8000.0             1.4        38.0         67.000000
2    2381740.0       -9999.0             2.8        28.0         75.000000
3        200.0        -790.0             2.2        29.0         59.516279
4        470.0         200.0             1.1        43.0         85.000000
..         ...           ...             ...         ...               ...
229      140.0        -119.0             1.9        37.0          0.000000
230   266000.0        5600.0             2.2        32.0         95.000000
231   527970.0      -29914.0             3.6        19.0         37.000000
232   743390.0       -5000.0             4.2        17.0         46.000000
233   386850.0       -9999.0             3.4        18.0         37.000000

     world_share
0           0.53
1           0.04
2           0.57
3           0.00
4           0.00
..           ...
229         0.00
230         0.01
231         0.43
232         0.26
233         0.21

[234 rows x 11 columns]

In [ ]:
mode = df['population_urban'].mode()
print(mode)
df['population_urban'].fillna(mode, inplace=True)
print(df)

0    59.516279
Name: population_urban, dtype: float64
             country  population  yearly_change  net_change  density  \
0        Afghanistan  42239854.0           2.70   1111083.0     65.0
1            Albania   2832439.0          -0.35     -9882.0    103.0
2            Algeria  45606480.0           1.57    703255.0     19.0
3     American Samoa     43914.0          -0.81      -359.0    220.0
4            Andorra     80088.0           0.33       264.0    170.0
..               ...         ...            ...         ...      ...
229  Wallis & Futuna     11502.0          -0.60       -70.0     82.0
230   Western Sahara    587259.0           1.96     11273.0      2.0
231            Yemen  34449825.0           2.24    753211.0     65.0
232           Zambia  20569737.0           2.76    552062.0     28.0
233         Zimbabwe  16665409.0           2.11    344872.0     43.0

     land_area  net_migrants  fertility_rate  median_age  population_urban  \
0     652860.0      -65846.0             4.4        17.0         26.000000
1      27400.0       -8000.0             1.4        38.0         67.000000
2    2381740.0       -9999.0             2.8        28.0         75.000000
3        200.0        -790.0             2.2        29.0         59.516279
4        470.0         200.0             1.1        43.0         85.000000
..         ...           ...             ...         ...               ...
229      140.0        -119.0             1.9        37.0          0.000000
230   266000.0        5600.0             2.2        32.0         95.000000
231   527970.0      -29914.0             3.6        19.0         37.000000
232   743390.0       -5000.0             4.2        17.0         46.000000
233   386850.0       -9999.0             3.4        18.0         37.000000

     world_share
0           0.53
1           0.04
2           0.57
3           0.00
4           0.00
..           ...
229         0.00
230         0.01
231         0.43
232         0.26
233         0.21

[234 rows x 11 columns]

In [ ]:
duplicates = df.duplicated()
print(duplicates)

0      False
1      False
2      False
3      False
4      False
       ...
229    False
230    False
231    False
232    False
233    False
Length: 234, dtype: bool

In [ ]:
df.drop_duplicates()

,country,population,yearly_change,net_change,density,land_area,net_migrants,fertility_rate,median_age,population_urban,world_share
0,Afghanistan,42239854.0,2.70,1111083.0,65.0,652860.0,-65846.0,4.4,17.0,26.000000,0.53
1,Albania,2832439.0,-0.35,-9882.0,103.0,27400.0,-8000.0,1.4,38.0,67.000000,0.04
2,Algeria,45606480.0,1.57,703255.0,19.0,2381740.0,-9999.0,2.8,28.0,75.000000,0.57
3,American Samoa,43914.0,-0.81,-359.0,220.0,200.0,-790.0,2.2,29.0,59.516279,0.00
4,Andorra,80088.0,0.33,264.0,170.0,470.0,200.0,1.1,43.0,85.000000,0.00
...,...,...,...,...,...,...,...,...,...,...,...
229,Wallis & Futuna,11502.0,-0.60,-70.0,82.0,140.0,-119.0,1.9,37.0,0.000000,0.00
230,Western Sahara,587259.0,1.96,11273.0,2.0,266000.0,5600.0,2.2,32.0,95.000000,0.01
231,Yemen,34449825.0,2.24,753211.0,65.0,527970.0,-29914.0,3.6,19.0,37.000000,0.43
232,Zambia,20569737.0,2.76,552062.0,28.0,743390.0,-5000.0,4.2,17.0,46.000000,0.26
233,Zimbabwe,16665409.0,2.11,344872.0,43.0,386850.0,-9999.0,3.4,18.0,37.000000,0.21